# Generated by Django 3.0.5 on 2020-05-28 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile/')),
                ('account_type', models.CharField(choices=[('teacher', 'teacher'), ('student', 'student')], max_length=10, verbose_name='you are a ')),
                ('city', models.CharField(choices=[('Cairo', 'Cairo'), ('Giza', 'Giza'), ('Alexandria', 'Alexandria'), ('Dakahlia', 'Dakahlia'), ('Red Sea', 'Red Sea'), ('Beheira', 'Beheira'), ('Fayoum', 'Fayoum'), ('Gharbiya', 'Gharbiya'), ('Ismailia', 'Ismailia'), ('Monofia', 'Monofia'), ('Minya', 'Minya'), ('Qaliubiya', 'Qaliubiya'), ('New Valley', 'New Valley'), ('Suez', 'Suez'), ('Aswan', 'Aswan'), ('Assiut', 'Assiut'), ('Beni Suef', 'Beni Suef'), ('Port Said', 'Port Said'), ('Damietta', 'Damietta'), ('Sharkia', 'Sharkia'), ('South Sinai', 'South Sinai'), ('Kafr Al sheikh', 'studeKafr Al sheikhnt'), ('Matrouh', 'Matrouh'), ('Luxor', 'Luxor'), ('Qena', 'Qena'), ('North Sinai', 'North Sinai"'), ('Sohag', 'Sohag')], max_length=30)),
                ('address', models.CharField(max_length=60)),
                ('Mobail', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
