# Generated by Django 3.0.5 on 2020-05-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200528_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subject',
            field=models.CharField(default='s', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.CharField(default='s', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('Cairo', 'Cairo'), ('Giza', 'Giza'), ('Alexandria', 'Alexandria'), ('Dakahlia', 'Dakahlia'), ('Red Sea', 'Red Sea'), ('Beheira', 'Beheira'), ('Fayoum', 'Fayoum'), ('Gharbiya', 'Gharbiya'), ('Ismailia', 'Ismailia'), ('Monofia', 'Monofia'), ('Minya', 'Minya'), ('Qaliubiya', 'Qaliubiya'), ('New Valley', 'New Valley'), ('Suez', 'Suez'), ('Aswan', 'Aswan'), ('Assiut', 'Assiut'), ('Beni Suef', 'Beni Suef'), ('Port Said', 'Port Said'), ('Damietta', 'Damietta'), ('Sharkia', 'Sharkia'), ('South Sinai', 'South Sinai'), ('Kafr Al sheikh', 'studeKafr Al sheikhnt'), ('Matrouh', 'Matrouh'), ('Luxor', 'Luxor'), ('Qena', 'Qena'), ('North Sinai', 'North Sinai'), ('Sohag', 'Sohag')], max_length=30),
        ),
    ]
