# Generated by Django 3.0.5 on 2020-05-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200529_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='acc_activated',
            field=models.BooleanField(default=False),
        ),
    ]
