# Generated by Django 3.0.5 on 2020-06-03 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='discription',
            new_name='description',
        ),
    ]
