# Generated by Django 3.0.5 on 2020-06-03 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0011_auto_20200603_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='school_name',
            field=models.CharField(default='sanwya', max_length=160),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('teacher', 'teacher'), ('student', 'student')], max_length=10, verbose_name="you are a *can't change later*  "),
        ),
        migrations.CreateModel(
            name='TeacherFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_file', models.FileField(upload_to='teacher files/')),
                ('file_name', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
