# Generated by Django 3.0.5 on 2020-06-03 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200603_0557'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherFile',
        ),
    ]
